/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import walletcontrol.ControlCompras;
import walletcontrol.ControlVentas;
import walletcontrol.Persona;

/**
 *
 * @author Eduardo
 */
public class Dashboard extends javax.swing.JFrame {

         ControlCompras controlBreakdown=new ControlCompras();
         ControlVentas ventasBreakdown=new ControlVentas();
           ArrayList<Persona> arrayBreak=new ArrayList<>();
           ArrayList<Persona> arrayVentas=new ArrayList<>();
           
           double sumaPaypal = 0,sumaPayza=0,sumaPayeer=0,sumaPayoneer=0,
                    sumaNeteller=0,sumaBitcoin=0,sumaEthereum=0,sumaSTP=0,
                    sumaGiftcard=0,sumaSkrill=0;
            int paypal = 0, payza=0,payeer=0,payoneer=0,neteller=0,bitcoin=0,
                    ethereum=0,stp=0,giftcard=0,skrill=0;
            double total;
            double sumaForo = 0,sumaFace = 0, sumaInsta = 0,sumaAIR = 0;
            double parseSuma;
            int foroPtc = 0,facebook = 0,Instagram = 0,airTM=0;
            DecimalFormat formatter = new DecimalFormat("#0.00");
            
    public Dashboard() {
        initComponents();
        comprasBreakDown();
        orgienComprasBreak();
        procesadorComprasBreak();
        PanelVentas.setVisible(false);
        ventasBreakDown();
        origenVentasBreak();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        headerTittle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelCompras = new javax.swing.JPanel();
        subPanelCompras1 = new javax.swing.JPanel();
        totalCompras = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        subPanelCompras2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        subPanelCompras6 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        PanelVentas = new javax.swing.JPanel();
        subPanelVentas1 = new javax.swing.JPanel();
        totalVentas = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        subPanelVentas = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        subPanelVentas2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(66, 66, 66));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerTittle.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        headerTittle.setForeground(new java.awt.Color(255, 255, 255));
        headerTittle.setText("Resumen de operaciones");
        Header.add(headerTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Literature_30px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 11, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Home_24px_1.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        Header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 11, -1, -1));

        jPanel3.setBackground(new java.awt.Color(66, 66, 66));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Add_Shopping_Cart_24px_1.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Header.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 60, 45));

        jPanel4.setBackground(new java.awt.Color(39, 174, 96));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Return_Purchase_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
        );

        Header.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 45));

        jPanel5.setBackground(new java.awt.Color(231, 76, 60));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(55, 55));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Currency_Exchange_24px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(20, 20, 20))
        );

        Header.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 60, 45));

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 841, 154));

        PanelCompras.setBackground(new java.awt.Color(255, 255, 255));
        PanelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subPanelCompras1.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        subPanelCompras1.setBorder(dropShadowBorder1);

        totalCompras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalCompras.setForeground(new java.awt.Color(39, 174, 96));
        totalCompras.setText("30");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel10.setText("compras concretadas");

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(39, 174, 96));
        jLabel11.setText("10");

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel12.setText("realizadas esta semana");

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel9.setText("El");

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 87, 34));
        jLabel13.setText("70%");

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel14.setText("proviene de Instagram");

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 136, 229));
        jLabel15.setText("Paypal");

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel16.setText("es el procesador mas usado");

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel17.setText("Procesador con mas ingresos");

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 87, 34));
        jLabel18.setText("Payoneer");

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 87, 34));
        jLabel19.setText("$315");

        javax.swing.GroupLayout subPanelCompras1Layout = new javax.swing.GroupLayout(subPanelCompras1);
        subPanelCompras1.setLayout(subPanelCompras1Layout);
        subPanelCompras1Layout.setHorizontalGroup(
            subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelCompras1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(totalCompras)
                .addGap(8, 8, 8)
                .addComponent(jLabel10))
            .addGroup(subPanelCompras1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addComponent(jLabel12))
            .addGroup(subPanelCompras1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(jLabel14))
            .addGroup(subPanelCompras1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(6, 6, 6)
                .addComponent(jLabel16))
            .addGroup(subPanelCompras1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(7, 7, 7)
                .addComponent(jLabel18)
                .addGap(6, 6, 6)
                .addComponent(jLabel19))
        );
        subPanelCompras1Layout.setVerticalGroup(
            subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelCompras1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalCompras)
                    .addGroup(subPanelCompras1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)))
                .addGap(6, 6, 6)
                .addGroup(subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(subPanelCompras1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12)))
                .addGap(6, 6, 6)
                .addGroup(subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(subPanelCompras1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))))
                .addGap(10, 10, 10)
                .addGroup(subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(subPanelCompras1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16)))
                .addGap(6, 6, 6)
                .addGroup(subPanelCompras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelCompras1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel17))
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)))
        );

        PanelCompras.add(subPanelCompras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 190));

        subPanelCompras2.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        subPanelCompras2.setBorder(dropShadowBorder2);

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(30, 136, 229));
        jLabel20.setText("Foro-PTC");

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(30, 136, 229));
        jLabel21.setText("Facebook");

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(30, 136, 229));
        jLabel22.setText("Instagram");

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(30, 136, 229));
        jLabel23.setText("AirTM");

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel24.setText("171.98$ en 12 compras");

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel25.setText("No se han registrado ");

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel26.setText("No se han registrado ");

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel27.setText("No se han registrado compras");

        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(39, 174, 96));
        jLabel28.setText("0.0%");

        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(39, 174, 96));
        jLabel29.setText("0.0%");

        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(39, 174, 96));
        jLabel30.setText("0.0%");

        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(39, 174, 96));
        jLabel31.setText("0.0%");

        javax.swing.GroupLayout subPanelCompras2Layout = new javax.swing.GroupLayout(subPanelCompras2);
        subPanelCompras2.setLayout(subPanelCompras2Layout);
        subPanelCompras2Layout.setHorizontalGroup(
            subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelCompras2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelCompras2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26))
                    .addGroup(subPanelCompras2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(subPanelCompras2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(subPanelCompras2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        subPanelCompras2Layout.setVerticalGroup(
            subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelCompras2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelCompras2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(jLabel31))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        PanelCompras.add(subPanelCompras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 390, 190));

        subPanelCompras6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        subPanelCompras6.setBorder(dropShadowBorder3);
        subPanelCompras6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel85.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(30, 136, 229));
        jLabel85.setText("Paypal");
        subPanelCompras6.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 23, -1, -1));

        jLabel86.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(30, 136, 229));
        jLabel86.setText("Payza");
        subPanelCompras6.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 55, -1, -1));

        jLabel87.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(30, 136, 229));
        jLabel87.setText("Payoneer");
        subPanelCompras6.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, -1, -1));

        jLabel88.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(30, 136, 229));
        jLabel88.setText("Payeer");
        subPanelCompras6.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 120, -1, -1));

        jLabel89.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(30, 136, 229));
        jLabel89.setText("Bitcoin");
        subPanelCompras6.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 153, -1, -1));

        jLabel90.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(30, 136, 229));
        jLabel90.setText("Giftcard");
        subPanelCompras6.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 55, -1, -1));

        jLabel91.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(30, 136, 229));
        jLabel91.setText("Neteller");
        subPanelCompras6.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 87, -1, -1));

        jLabel92.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(30, 136, 229));
        jLabel92.setText("Ethereum");
        subPanelCompras6.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 23, -1, -1));

        jLabel93.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(30, 136, 229));
        jLabel93.setText("STP");
        subPanelCompras6.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 153, -1, -1));

        jLabel94.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(30, 136, 229));
        jLabel94.setText("Skrill");
        subPanelCompras6.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel95.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel95.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 27, -1, -1));

        jLabel96.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel96.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 59, -1, -1));

        jLabel97.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel97.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 91, -1, -1));

        jLabel98.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel98.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 124, -1, -1));

        jLabel99.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel99.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 157, -1, -1));

        jLabel100.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(39, 174, 96));
        jLabel100.setText("0.0%");
        subPanelCompras6.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 27, -1, -1));

        jLabel101.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(39, 174, 96));
        jLabel101.setText("0.0%");
        subPanelCompras6.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 60, -1, -1));

        jLabel102.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(39, 174, 96));
        jLabel102.setText("0.0%");
        subPanelCompras6.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 95, -1, -1));

        jLabel103.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(39, 174, 96));
        jLabel103.setText("0.0%");
        subPanelCompras6.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 125, -1, -1));

        jLabel104.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(39, 174, 96));
        jLabel104.setText("0.0%");
        subPanelCompras6.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 157, -1, -1));

        jLabel105.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel105.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 27, -1, -1));

        jLabel106.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel106.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 59, -1, -1));

        jLabel107.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel107.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 91, -1, -1));

        jLabel108.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel108.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 124, -1, -1));

        jLabel109.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel109.setText("No se han registrado compras");
        subPanelCompras6.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 157, -1, -1));

        jLabel110.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(39, 174, 96));
        jLabel110.setText("0.0%");
        subPanelCompras6.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 27, -1, -1));

        jLabel111.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(39, 174, 96));
        jLabel111.setText("0.0%");
        subPanelCompras6.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 60, -1, -1));

        jLabel112.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(39, 174, 96));
        jLabel112.setText("0.0%");
        subPanelCompras6.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 95, -1, -1));

        jLabel113.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(39, 174, 96));
        jLabel113.setText("0.0%");
        subPanelCompras6.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 125, -1, -1));

        jLabel114.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(39, 174, 96));
        jLabel114.setText("0.0%");
        subPanelCompras6.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 157, -1, 22));

        PanelCompras.add(subPanelCompras6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 790, 200));

        jPanel1.add(PanelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 160, 830, 460));

        PanelVentas.setBackground(new java.awt.Color(255, 255, 255));
        PanelVentas.setPreferredSize(new java.awt.Dimension(820, 430));
        PanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subPanelVentas1.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        subPanelVentas1.setBorder(dropShadowBorder4);
        subPanelVentas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalVentas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalVentas.setForeground(new java.awt.Color(39, 174, 96));
        totalVentas.setText("30");
        subPanelVentas1.add(totalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, -1));

        jLabel62.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel62.setText("Ventas concretadas");
        subPanelVentas1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 20, -1, -1));

        jLabel63.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(39, 174, 96));
        jLabel63.setText("10");
        subPanelVentas1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, -1, -1));

        jLabel64.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel64.setText("realizadas esta semana");
        subPanelVentas1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 55, -1, -1));

        jLabel65.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel65.setText("El");
        subPanelVentas1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 88, -1, -1));

        jLabel66.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 87, 34));
        jLabel66.setText("70%");
        subPanelVentas1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 85, -1, -1));

        jLabel67.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel67.setText("proviene de Instagram");
        subPanelVentas1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 88, -1, -1));

        jLabel68.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(30, 136, 229));
        jLabel68.setText("Paypal");
        subPanelVentas1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 119, -1, -1));

        jLabel69.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel69.setText("es el procesador mas usado");
        subPanelVentas1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 123, -1, -1));

        jLabel70.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel70.setText("Procesador con mas ingresos");
        subPanelVentas1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 153, -1, -1));

        jLabel71.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 87, 34));
        jLabel71.setText("Payoneer");
        subPanelVentas1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 149, -1, -1));

        jLabel72.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 87, 34));
        jLabel72.setText("$315");
        subPanelVentas1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 149, -1, -1));

        PanelVentas.add(subPanelVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 190));

        subPanelVentas.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        subPanelVentas.setBorder(dropShadowBorder5);
        subPanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(30, 136, 229));
        jLabel73.setText("Foro-PTC");
        subPanelVentas.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 25, -1, -1));

        jLabel74.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(30, 136, 229));
        jLabel74.setText("Facebook");
        subPanelVentas.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 61, -1, -1));

        jLabel75.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(30, 136, 229));
        jLabel75.setText("Instagram");
        subPanelVentas.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 97, -1, -1));

        jLabel76.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(30, 136, 229));
        jLabel76.setText("AirTM");
        subPanelVentas.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 133, -1, -1));

        jLabel77.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel77.setText("No se han registrado ventas");
        subPanelVentas.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 29, -1, -1));

        jLabel78.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel78.setText("No se han registrado ventas");
        subPanelVentas.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 65, -1, -1));

        jLabel79.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel79.setText("No se han registrado ventas");
        subPanelVentas.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 101, -1, -1));

        jLabel80.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel80.setText("No se han registrado ventas");
        subPanelVentas.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 137, -1, -1));

        jLabel81.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(39, 174, 96));
        jLabel81.setText("0.0%");
        subPanelVentas.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 29, -1, -1));

        jLabel82.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(39, 174, 96));
        jLabel82.setText("0.0%");
        subPanelVentas.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 65, -1, -1));

        jLabel83.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(39, 174, 96));
        jLabel83.setText("0.0%");
        subPanelVentas.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 101, -1, -1));

        jLabel84.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(39, 174, 96));
        jLabel84.setText("0.0%");
        subPanelVentas.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 137, -1, -1));

        PanelVentas.add(subPanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 390, 190));

        subPanelVentas2.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        subPanelVentas2.setBorder(dropShadowBorder6);
        subPanelVentas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(30, 136, 229));
        jLabel32.setText("Paypal");
        subPanelVentas2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 23, -1, -1));

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(30, 136, 229));
        jLabel33.setText("Payza");
        subPanelVentas2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 55, -1, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(30, 136, 229));
        jLabel34.setText("Payoneer");
        subPanelVentas2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, -1, -1));

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(30, 136, 229));
        jLabel35.setText("Payeer");
        subPanelVentas2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 120, -1, -1));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(30, 136, 229));
        jLabel36.setText("Bitcoin");
        subPanelVentas2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 153, -1, -1));

        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(30, 136, 229));
        jLabel37.setText("Giftcard");
        subPanelVentas2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 55, -1, -1));

        jLabel38.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(30, 136, 229));
        jLabel38.setText("Neteller");
        subPanelVentas2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 87, -1, -1));

        jLabel39.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(30, 136, 229));
        jLabel39.setText("Ethereum");
        subPanelVentas2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 23, -1, -1));

        jLabel40.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(30, 136, 229));
        jLabel40.setText("STP");
        subPanelVentas2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 153, -1, -1));

        jLabel41.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(30, 136, 229));
        jLabel41.setText("Skrill");
        subPanelVentas2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel42.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel42.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 27, -1, -1));

        jLabel43.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel43.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 59, -1, -1));

        jLabel44.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel44.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 91, -1, -1));

        jLabel45.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel45.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 124, -1, -1));

        jLabel46.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel46.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 157, -1, -1));

        jLabel47.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(39, 174, 96));
        jLabel47.setText("0.0%");
        subPanelVentas2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 27, -1, -1));

        jLabel48.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(39, 174, 96));
        jLabel48.setText("0.0%");
        subPanelVentas2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 60, -1, -1));

        jLabel49.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(39, 174, 96));
        jLabel49.setText("0.0%");
        subPanelVentas2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 95, -1, -1));

        jLabel50.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(39, 174, 96));
        jLabel50.setText("0.0%");
        subPanelVentas2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 125, -1, -1));

        jLabel51.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(39, 174, 96));
        jLabel51.setText("0.0%");
        subPanelVentas2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 157, -1, -1));

        jLabel52.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel52.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 27, -1, -1));

        jLabel53.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel53.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 59, -1, -1));

        jLabel54.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel54.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 91, -1, -1));

        jLabel55.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel55.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 124, -1, -1));

        jLabel56.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel56.setText("No se han registrado ventas");
        subPanelVentas2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 157, -1, -1));

        jLabel57.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(39, 174, 96));
        jLabel57.setText("0.0%");
        subPanelVentas2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 27, -1, -1));

        jLabel58.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(39, 174, 96));
        jLabel58.setText("0.0%");
        subPanelVentas2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 60, -1, -1));

        jLabel59.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(39, 174, 96));
        jLabel59.setText("0.0%");
        subPanelVentas2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 95, -1, -1));

        jLabel60.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(39, 174, 96));
        jLabel60.setText("0.0%");
        subPanelVentas2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 125, -1, -1));

        jLabel61.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(39, 174, 96));
        jLabel61.setText("0.0%");
        subPanelVentas2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 157, -1, 22));

        PanelVentas.add(subPanelVentas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 790, 200));

        jPanel1.add(PanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 160, 830, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        new Home1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
             try {
                 new Historial().setVisible(true);
                 this.dispose();
             } catch (IOException ex) {
                 Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jLabel2MousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
       jPanel4.setBackground(new java.awt.Color(66, 66, 66));
       jPanel3.setBackground(new java.awt.Color(52, 152, 219));
       jPanel5.setBackground(new java.awt.Color(231,76,60));
       PanelVentas.setVisible(true);
       PanelCompras.setVisible(false);
       
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
       jPanel3.setBackground(new java.awt.Color(66, 66, 66));
       jPanel4.setBackground(new java.awt.Color(39,174,96));
       jPanel5.setBackground(new java.awt.Color(231,76,60));
       PanelCompras.setVisible(true);
       PanelVentas.setVisible(false);
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
       jPanel5.setBackground(new java.awt.Color(66,66,66));
       jPanel3.setBackground(new java.awt.Color(52, 152, 219));
       jPanel4.setBackground(new java.awt.Color(39,174,96));
       
    }//GEN-LAST:event_jPanel5MousePressed

    
    
    private void comprasBreakDown() {
        try {
            
            arrayBreak=controlBreakdown.retornaPersona();
                        
            total = arrayBreak.size();
            totalCompras.setText(String.valueOf(total));
            
            
            
            
            
            for (int i = 0; i <arrayBreak.size(); i++) {
                
                if(arrayBreak.get(i).getOrigen().equals("Foro-PTC")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaForo += parseSuma;
                    foroPtc++;
                }else if(arrayBreak.get(i).getOrigen().equals("Facebook")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaFace += parseSuma;
                    facebook++;
                }else if(arrayBreak.get(i).getOrigen().equals("Instagram")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaInsta +=parseSuma;
                    Instagram++; 
                }else if(arrayBreak.get(i).getOrigen().equals("AirTM")) {
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaAIR += parseSuma;
                    airTM++;  
                }
                
                if(arrayBreak.get(i).getProcesador().equals("Paypal")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPaypal+=parseSuma;
                    paypal++;
                }else if(arrayBreak.get(i).getProcesador().equals("Payza")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPayza+=parseSuma;
                    payza++;
                }else if(arrayBreak.get(i).getProcesador().equals("Payoneer")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPayoneer+=parseSuma;
                    payoneer++;
                }else if(arrayBreak.get(i).getProcesador().equals("Bitcoin")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaBitcoin+=parseSuma;
                    bitcoin++;
                }else if(arrayBreak.get(i).getProcesador().equals("Ethereum")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaEthereum+=parseSuma;
                    ethereum++;
                }else if(arrayBreak.get(i).getProcesador().equals("Skrill")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaSkrill+=parseSuma;
                    skrill++;
                }else if(arrayBreak.get(i).getProcesador().equals("Neteller")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaNeteller+=parseSuma;
                    neteller++;
                }else if(arrayBreak.get(i).getProcesador().equals("Giftcard")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaGiftcard+=parseSuma;
                    giftcard++;
                }else if(arrayBreak.get(i).getProcesador().equals("STP")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaSTP+=parseSuma;
                    stp++;
                }else if(arrayBreak.get(i).getProcesador().equals("Payeer")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPayeer+=parseSuma;
                    payeer++;
                }

            }    
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    private void orgienComprasBreak(){
        if(foroPtc!=0){
           
            
            double porcentForo=((foroPtc*100)/total);
            String porcentajeForo=String.format( "%.2f", porcentForo );
            String sumaForo2=formatter.format(sumaForo);
            jLabel28.setText(porcentajeForo+"%");
            jLabel24.setText(sumaForo2+"$ en "+foroPtc+" compras");

                if(foroPtc>facebook && foroPtc>Instagram && foroPtc>airTM){
                    jLabel14.setText("provienen de Foro-PTC");
                    jLabel13.setText(String.valueOf(porcentajeForo)+"%");
     
            }
            }
            
            
            if(facebook!=0){
            double porcentFace=((facebook*100)/total);
            String porcentajeFace=formatter.format(porcentFace);
            String sumaFace2=formatter.format(sumaFace);
            jLabel29.setText(porcentajeFace+"%");
            jLabel25.setText(sumaFace2+"$ en "+facebook+" compras");
                if (facebook>Instagram && facebook>airTM) {
                    jLabel14.setText("provienen de Facebook");
                    jLabel13.setText(String.valueOf(porcentajeFace)+"%");
                }
            }
            
            if(Instagram!=0){
            double porcentInsta=((Instagram*100)/total);
            String porcentajeInsta=formatter.format(porcentInsta);
            String sumaInsta2=formatter.format(sumaInsta);
            jLabel30.setText(porcentajeInsta+"%");
            jLabel26.setText(sumaInsta2+"$ en "+Instagram+" compras");
                if (Instagram>airTM) {
                    jLabel14.setText("provienen de Instagram");
                    jLabel13.setText(String.valueOf(porcentajeInsta)+"%");
                }
            }
            if(airTM!=0){
            double porcentAIR=((airTM*100)/total);
            String porcentajeAIR=formatter.format(porcentAIR);
            String sumaAIR2=formatter.format(sumaAIR);
            jLabel31.setText(porcentajeAIR+"%");
            jLabel27.setText(sumaAIR2+"$ en "+airTM+" compras");
                if (airTM>foroPtc && airTM>Instagram && airTM>facebook) {
                    jLabel14.setText("provienen de AirTM");
                    jLabel13.setText(String.valueOf(porcentajeAIR)+"%");
                } 
            }
    }
    private void procesadorComprasBreak(){
        if(paypal!=0){
                double porcentPaypal=((paypal*100)/total);
                String porcentajePaypal=formatter.format(porcentPaypal);
                String sumaPaypal2=formatter.format(sumaPaypal);
                jLabel47.setText(porcentajePaypal+"%");
                jLabel42.setText(sumaPaypal2+"$ en "+paypal+" compras");
                
                if(paypal>=payza && paypal>=payeer && paypal>=payoneer && paypal>=skrill 
                        && paypal>=stp && paypal>=bitcoin && paypal>=ethereum 
                        && paypal>=giftcard && paypal>=neteller){
                    
                    jLabel15.setText("PayPal");
                }
            }
            if(payza!=0){
                double porcentPayza=((payza*100)/total);
                String porcentajePayza=formatter.format(porcentPayza);
                String sumaPayza2=formatter.format(sumaPayza);
                jLabel48.setText(porcentajePayza+"%");
                jLabel43.setText(sumaPayza2+"$ en "+payza+" compras");
                if(payza>=payeer && payza>=payoneer && payza>=skrill 
                        && payza>=stp && payza>=bitcoin && payza>=ethereum 
                        && payza>=giftcard && payza>=neteller && payza>=paypal){
                    
                    jLabel15.setText("Payza");
                }
            }
            if(payeer!=0){
                double porcentPayeer=((payeer*100)/total);
                String porcentajePayeer=formatter.format(porcentPayeer);
                String sumaPayeer2=formatter.format(sumaPayeer);
                jLabel50.setText(porcentajePayeer+"%");
                jLabel45.setText(sumaPayeer2+"$ en "+payeer+" compras");
                if(payeer>=payza && payeer>=payoneer && payeer>=skrill 
                        && payeer>=stp && payeer>=bitcoin && payeer>=ethereum 
                        && payeer>=giftcard && payeer>=neteller && payeer>=paypal){
                    
                    jLabel15.setText("Payeer");
                }
            }
            if(payoneer!=0){
                double porcentPayoneer=((payoneer*100)/total);
                String porcentajePayoneer=formatter.format(porcentPayoneer);
                String sumaPayoneer2=formatter.format(sumaPayoneer);
                jLabel49.setText(porcentajePayoneer+"%");
                jLabel44.setText(sumaPayoneer2+"$ en "+payoneer+" compras");         
                 if(payoneer>=payeer && payoneer>=payza && payoneer>=skrill 
                        && payoneer>=stp && payoneer>=bitcoin && payoneer>=ethereum 
                        && payoneer>=giftcard && payoneer>=neteller && payoneer>=paypal){           
                    jLabel15.setText("Payoneer");
                }
            }
            if(skrill!=0){
                double porcentSkrill=((skrill*100)/total);
                String porcentajeSkrill=formatter.format(porcentSkrill);
                String sumaSkrill2=formatter.format(sumaSkrill);
                jLabel60.setText(porcentajeSkrill+"%");
                jLabel55.setText(sumaSkrill2+"$ en "+skrill+" compras");
                 if(skrill>=payeer && skrill>=payoneer && skrill>=payza 
                        && skrill>=stp && skrill>=bitcoin && skrill>=ethereum 
                        && skrill>=giftcard && skrill>=neteller && skrill>=paypal){
                    jLabel15.setText("Skrill");
                }
            }
            
            if(stp!=0){
                double porcentSTP=((stp*100)/total);
                String porcentajeSTP=formatter.format(porcentSTP);
                String sumaSTP2=formatter.format(sumaSTP);
                jLabel61.setText(porcentajeSTP+"%");
                jLabel56.setText(sumaSTP2+"$ en "+stp+" compras");
                 if(stp>=payeer && stp>=payoneer && stp>=skrill 
                        && stp>=payza && stp>=bitcoin && stp>=ethereum 
                        && stp>=giftcard && stp>=neteller && stp>=paypal){
                    jLabel15.setText("STP");
                }
            }
            if(bitcoin!=0){
                double porcentBitcoin=((bitcoin*100)/total);
                String porcentajeBitcoin=formatter.format(porcentBitcoin);
                String sumaBitcoin2=formatter.format(sumaBitcoin);
                jLabel51.setText(porcentajeBitcoin+"%");
                jLabel46.setText(sumaBitcoin2+"$ en "+bitcoin+" compras");
                 if(bitcoin>=payeer && bitcoin>=payoneer && bitcoin>=skrill 
                        && bitcoin>=stp && bitcoin>=payza && bitcoin>=ethereum 
                        && bitcoin>=giftcard && bitcoin>=neteller && bitcoin>=paypal){
                    jLabel15.setText("Bitcoin");
                }
            }
            if(ethereum!=0){
                double porcentEthereum=((ethereum*100)/total);
                String porcentajeEthereum=formatter.format(porcentEthereum);
                String sumaEthereum2=formatter.format(sumaEthereum);
                jLabel57.setText(porcentajeEthereum+"%");
                jLabel52.setText(sumaEthereum2+"$ en "+ethereum+" compras");
                 if(ethereum>=payeer && ethereum>=payoneer && ethereum>=skrill 
                        && ethereum>=stp && ethereum>=bitcoin && ethereum>=payza 
                        && ethereum>=giftcard && ethereum>=neteller && ethereum>=paypal){
                    jLabel15.setText("Ethereum");
                }
            }
            if(giftcard!=0){
                double porcentGiftcard=((giftcard*100)/total);
                String porcentajeGiftcard=formatter.format(porcentGiftcard);
                String sumaGiftcard2=formatter.format(sumaGiftcard);
                jLabel58.setText(porcentajeGiftcard+"%");
                jLabel53.setText(sumaGiftcard2+"$ en "+giftcard+" compras");
                 if(giftcard>=payeer && giftcard>=payoneer && giftcard>=skrill 
                        && giftcard>=stp && giftcard>=bitcoin && giftcard>=ethereum 
                        && giftcard>=payza && giftcard>=neteller && giftcard>=paypal){
                    jLabel15.setText("Giftcard");
                }
            }
                if(neteller!=0){
                double porcentNeteller=((neteller*100)/total);
                String porcentajeNeteller=formatter.format(porcentNeteller);
                String sumaNeteller2=formatter.format(sumaNeteller);
                jLabel59.setText(porcentajeNeteller+"%");
                jLabel54.setText(sumaNeteller2+"$ en "+neteller+" compras");
                
                if(neteller>=payeer && neteller>=payoneer && neteller>=skrill 
                        && neteller>=stp && neteller>=neteller && neteller>=ethereum 
                        && neteller>=giftcard && neteller>=payza && neteller>=paypal){
                    
                    jLabel15.setText("Neteller");
                }
            }
    }
    
    private void ventasBreakDown(){
        try {
            
            arrayVentas=ventasBreakdown.retornaPersonaVentas();
                        
            total = arrayVentas.size();
            totalVentas.setText(String.valueOf(total));

            for (int i = 0; i <arrayBreak.size(); i++) {
                
                if(arrayBreak.get(i).getOrigen().equals("Foro-PTC")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaForo += parseSuma;
                    foroPtc++;
                }else if(arrayBreak.get(i).getOrigen().equals("Facebook")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaFace += parseSuma;
                    facebook++;
                }else if(arrayBreak.get(i).getOrigen().equals("Instagram")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaInsta +=parseSuma;
                    Instagram++; 
                }else if(arrayBreak.get(i).getOrigen().equals("AirTM")) {
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaAIR += parseSuma;
                    airTM++;  
                }
                
                if(arrayBreak.get(i).getProcesador().equals("Paypal")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPaypal+=parseSuma;
                    paypal++;
                }else if(arrayBreak.get(i).getProcesador().equals("Payza")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPayza+=parseSuma;
                    payza++;
                }else if(arrayBreak.get(i).getProcesador().equals("Payoneer")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPayoneer+=parseSuma;
                    payoneer++;
                }else if(arrayBreak.get(i).getProcesador().equals("Bitcoin")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaBitcoin+=parseSuma;
                    bitcoin++;
                }else if(arrayBreak.get(i).getProcesador().equals("Ethereum")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaEthereum+=parseSuma;
                    ethereum++;
                }else if(arrayBreak.get(i).getProcesador().equals("Skrill")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaSkrill+=parseSuma;
                    skrill++;
                }else if(arrayBreak.get(i).getProcesador().equals("Neteller")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaNeteller+=parseSuma;
                    neteller++;
                }else if(arrayBreak.get(i).getProcesador().equals("Giftcard")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaGiftcard+=parseSuma;
                    giftcard++;
                }else if(arrayBreak.get(i).getProcesador().equals("STP")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaSTP+=parseSuma;
                    stp++;
                }else if(arrayBreak.get(i).getProcesador().equals("Payeer")){
                    parseSuma = Double.parseDouble(arrayBreak.get(i).getMonto());
                    sumaPayeer+=parseSuma;
                    payeer++;
                }

            }   
            System.err.println(airTM);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    private void origenVentasBreak(){
    if(foroPtc!=0){ 
            double porcentForo=((foroPtc*100)/total);
            String porcentajeForo=String.format( "%.2f", porcentForo );
            String sumaForo2=formatter.format(sumaForo);
            jLabel81.setText(porcentajeForo+"%");
            jLabel77.setText(sumaForo2+"$ en "+foroPtc+" compras");

                if(foroPtc>facebook && foroPtc>Instagram && foroPtc>airTM){
                    jLabel67.setText("provienen de Foro-PTC");
                    jLabel66.setText(String.valueOf(porcentajeForo)+"%");
     
            }
            }
            
            
            if(facebook!=0){
            double porcentFace=((facebook*100)/total);
            String porcentajeFace=formatter.format(porcentFace);
            String sumaFace2=formatter.format(sumaFace);
            jLabel82.setText(porcentajeFace+"%");
            jLabel78.setText(sumaFace2+"$ en "+facebook+" compras");
                if (facebook>Instagram && facebook>airTM) {
                    jLabel67.setText("provienen de Facebook");
                    jLabel66.setText(String.valueOf(porcentajeFace)+"%");
                }
            }
            
            if(Instagram!=0){
            double porcentInsta=((Instagram*100)/total);
            String porcentajeInsta=formatter.format(porcentInsta);
            String sumaInsta2=formatter.format(sumaInsta);
            jLabel83.setText(porcentajeInsta+"%");
            jLabel79.setText(sumaInsta2+"$ en "+Instagram+" compras");
                if (Instagram>airTM) {
                    jLabel67.setText("provienen de Instagram");
                    jLabel66.setText(String.valueOf(porcentajeInsta)+"%");
                }
            }
            if(airTM!=0){
            double porcentAIR=((airTM*100)/total);
            String porcentajeAIR=formatter.format(porcentAIR);
            String sumaAIR2=formatter.format(sumaAIR);
            jLabel84.setText(porcentajeAIR+"%");
            jLabel80.setText(sumaAIR2+"$ en "+airTM+" compras");
                if (airTM>foroPtc && airTM>Instagram && airTM>facebook) {
                    jLabel67.setText("provienen de AirTM");
                    jLabel66.setText(String.valueOf(porcentajeAIR)+"%");
                } 
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel PanelCompras;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JLabel headerTittle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel subPanelCompras1;
    private javax.swing.JPanel subPanelCompras2;
    private javax.swing.JPanel subPanelCompras6;
    private javax.swing.JPanel subPanelVentas;
    private javax.swing.JPanel subPanelVentas1;
    private javax.swing.JPanel subPanelVentas2;
    private javax.swing.JLabel totalCompras;
    private javax.swing.JLabel totalVentas;
    // End of variables declaration//GEN-END:variables
}
