/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import walletcontrol.ControlCompras;
import walletcontrol.ClipboardKeyAdapter;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import walletcontrol.MatricesHistorial;
import walletcontrol.TextPrompt;

/**
 *
 * @author Eduardo Perfecto
 */
public class Historial extends javax.swing.JFrame {

    private static final long serialVersionUID = -5683020974161929770L;

    private TableRowSorter trsfiltro;
    private final ControlCompras control;
    private final File ficheroCompras=new File("C:\\ProgramData\\WalletControl.dat");
    private final File ficheroVentas=new File("C:\\ProgramData\\WalletControlVentas.dat");
    private final File ficheroExchange=new File("C:\\ProgramData\\WalletControlExchange.dat");
    //Cosntructor
    public Historial(String selectedTab) throws IOException, ClassNotFoundException {
        initComponents();
        this.control = new ControlCompras();
        setLocationRelativeTo(null);
        cargarTablaCompras();                                
        cargarTablaVentas();
        cargarTablaExchange();
        centrar(3,jXTable1);
        centrar(3,TablaVentas);  
        placeHolder();
        
        if (null!=selectedTab)switch (selectedTab) {
            case "Compras":
                comprasTab();
                break;
            case "Ventas":
                ventasTab();
                break;
            case "Exchange":
                exchangeTab();
                break;
            default:
                break;
        }
        
             
    }
    
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vistas/Logounico.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuCompras = new javax.swing.JPopupMenu();
        AbrirCompras = new javax.swing.JMenuItem();
        jPopupMenuVentas = new javax.swing.JPopupMenu();
        AbrirVenta = new javax.swing.JMenuItem();
        jPopupExchange = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonInicio = new javax.swing.JLabel();
        TituloVentana = new javax.swing.JLabel();
        AñadirCompra = new javax.swing.JLabel();
        ComprasBorrar = new javax.swing.JLabel();
        montoTotalVentas = new javax.swing.JLabel();
        montoTotalCompras = new javax.swing.JLabel();
        BuscarCompras = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        buscarIcono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabeltotalCompra = new javax.swing.JLabel();
        jLabeltotalVentas = new javax.swing.JLabel();
        tabVentas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BuscarVentas = new javax.swing.JTextField();
        VentasBorrar = new javax.swing.JLabel();
        AñadirVenta = new javax.swing.JLabel();
        tabCompras = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tabExchange = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BuscarExchange = new javax.swing.JTextField();
        AñadirExchange = new javax.swing.JLabel();
        ExchangeBorrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVentas = new org.jdesktop.swingx.JXTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaExchange = new org.jdesktop.swingx.JXTable();

        AbrirCompras.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        AbrirCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Open_24px.png"))); // NOI18N
        AbrirCompras.setText("Abrir");
        AbrirCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirComprasActionPerformed(evt);
            }
        });
        jPopupMenuCompras.add(AbrirCompras);

        AbrirVenta.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        AbrirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Open_24px.png"))); // NOI18N
        AbrirVenta.setText("Abrir");
        AbrirVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AbrirVentaMousePressed(evt);
            }
        });
        jPopupMenuVentas.add(AbrirVenta);

        jMenuItem1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Open_24px.png"))); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jPopupExchange.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(150);
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 71, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Home_24px_1.png"))); // NOI18N
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonInicioMousePressed(evt);
            }
        });
        jPanel2.add(BotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        TituloVentana.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        TituloVentana.setForeground(new java.awt.Color(255, 255, 255));
        TituloVentana.setText("Historico de transacciones");
        jPanel2.add(TituloVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        AñadirCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Add_List_24px_1_1.png"))); // NOI18N
        AñadirCompra.setToolTipText("Añade una compra.");
        AñadirCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AñadirCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AñadirCompraMousePressed(evt);
            }
        });
        jPanel2.add(AñadirCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 11, -1, -1));

        ComprasBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Waste_24px.png"))); // NOI18N
        ComprasBorrar.setToolTipText("Elimina todas las compras.");
        ComprasBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComprasBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComprasBorrarMousePressed(evt);
            }
        });
        jPanel2.add(ComprasBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 11, -1, -1));

        montoTotalVentas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        montoTotalVentas.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(montoTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 90, 30));

        montoTotalCompras.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        montoTotalCompras.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(montoTotalCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 90, 30));

        BuscarCompras.setBackground(new java.awt.Color(55, 71, 79));
        BuscarCompras.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        BuscarCompras.setForeground(new java.awt.Color(255, 255, 255));
        BuscarCompras.setBorder(null);
        BuscarCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarComprasKeyTyped(evt);
            }
        });
        jPanel2.add(BuscarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 134, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 102, 102));
        jComboBox2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Origen", "ID", "Fecha" }));
        jComboBox2.setToolTipText("");
        jComboBox2.setAutoscrolls(true);
        jComboBox2.setBorder(null);
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.setDoubleBuffered(true);
        jComboBox2.setFocusable(false);
        jComboBox2.setLightWeightPopupEnabled(false);
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, -1));

        buscarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Search_24px_1_1.png"))); // NOI18N
        jPanel2.add(buscarIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 110, 10));

        jLabeltotalCompra.setBackground(new java.awt.Color(255, 255, 255));
        jLabeltotalCompra.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabeltotalCompra.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltotalCompra.setText("Total en Compras:");
        jPanel2.add(jLabeltotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 220, 30));

        jLabeltotalVentas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabeltotalVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltotalVentas.setText("Total en Ventas:");
        jLabeltotalVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeltotalVentasMouseClicked(evt);
            }
        });
        jPanel2.add(jLabeltotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 200, 30));

        tabVentas.setBackground(new java.awt.Color(55, 71, 79));
        tabVentas.setToolTipText("Mientras esta pestaña este activa, las funciones de los botones agregar, borrar y buscar estan vinculadas a las Ventas.");
        tabVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabVentasMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Money_Bag_24px.png"))); // NOI18N

        javax.swing.GroupLayout tabVentasLayout = new javax.swing.GroupLayout(tabVentas);
        tabVentas.setLayout(tabVentasLayout);
        tabVentasLayout.setHorizontalGroup(
            tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tabVentasLayout.setVerticalGroup(
            tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabVentasLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel2.add(tabVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 50));

        BuscarVentas.setBackground(new java.awt.Color(55, 71, 79));
        BuscarVentas.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        BuscarVentas.setForeground(new java.awt.Color(255, 255, 255));
        BuscarVentas.setBorder(null);
        BuscarVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarVentasKeyTyped(evt);
            }
        });
        jPanel2.add(BuscarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 134, -1));

        VentasBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Waste_24px.png"))); // NOI18N
        VentasBorrar.setToolTipText("Elimina todas las ventas.");
        VentasBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VentasBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VentasBorrarMousePressed(evt);
            }
        });
        jPanel2.add(VentasBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 11, -1, -1));

        AñadirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Add_List_24px_1_1.png"))); // NOI18N
        AñadirVenta.setToolTipText("Añade una venta.");
        AñadirVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AñadirVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AñadirVentaMousePressed(evt);
            }
        });
        jPanel2.add(AñadirVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 11, -1, -1));

        tabCompras.setBackground(new java.awt.Color(0, 120, 215));
        tabCompras.setToolTipText("Mientras esta pestaña este activa, las funciones de los botones agregar, borrar y buscar estan vinculadas a las Compras.");
        tabCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabComprasMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Add_Shopping_Cart_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout tabComprasLayout = new javax.swing.GroupLayout(tabCompras);
        tabCompras.setLayout(tabComprasLayout);
        tabComprasLayout.setHorizontalGroup(
            tabComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabComprasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tabComprasLayout.setVerticalGroup(
            tabComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabComprasLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel2.add(tabCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        tabExchange.setBackground(new java.awt.Color(55, 71, 79));
        tabExchange.setToolTipText("Mientras esta pestaña este activa, las funciones de los botones agregar, borrar y buscar estan vinculadas a los Exchanges.");
        tabExchange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabExchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabExchangeMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Currency_Exchange_24px_2.png"))); // NOI18N

        javax.swing.GroupLayout tabExchangeLayout = new javax.swing.GroupLayout(tabExchange);
        tabExchange.setLayout(tabExchangeLayout);
        tabExchangeLayout.setHorizontalGroup(
            tabExchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabExchangeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tabExchangeLayout.setVerticalGroup(
            tabExchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabExchangeLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel2.add(tabExchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 50));

        BuscarExchange.setBackground(new java.awt.Color(55, 71, 79));
        BuscarExchange.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        BuscarExchange.setForeground(new java.awt.Color(255, 255, 255));
        BuscarExchange.setBorder(null);
        BuscarExchange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarExchangeKeyTyped(evt);
            }
        });
        jPanel2.add(BuscarExchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 134, -1));

        AñadirExchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Add_List_24px_1_1.png"))); // NOI18N
        AñadirExchange.setToolTipText("Añade un exchange.");
        AñadirExchange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AñadirExchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AñadirExchangeMousePressed(evt);
            }
        });
        jPanel2.add(AñadirExchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 11, -1, -1));

        ExchangeBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Waste_24px.png"))); // NOI18N
        ExchangeBorrar.setToolTipText("Elimina todos los exchanges.");
        ExchangeBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExchangeBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExchangeBorrarMousePressed(evt);
            }
        });
        jPanel2.add(ExchangeBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 11, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Origen", "Procesador", "Monto $", "ID", "Correo", "Fecha", "Directorio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaVentas.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));
        JTableHeader Theader=TablaVentas.getTableHeader();
        ((JLabel)Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        TablaVentas.setComponentPopupMenu(jPopupMenuVentas);
        TablaVentas.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        TablaVentas.setGridColor(new java.awt.Color(255, 255, 255));
        TablaVentas.setRowHeight(30);
        TablaVentas.setSelectionBackground(new java.awt.Color(39, 174, 96));
        jScrollPane1.setViewportView(TablaVentas);
        if (TablaVentas.getColumnModel().getColumnCount() > 0) {
            TablaVentas.getColumnModel().getColumn(0).setResizable(false);
            TablaVentas.getColumnModel().getColumn(1).setResizable(false);
            TablaVentas.getColumnModel().getColumn(2).setResizable(false);
            TablaVentas.getColumnModel().getColumn(3).setResizable(false);
            TablaVentas.getColumnModel().getColumn(4).setResizable(false);
            TablaVentas.getColumnModel().getColumn(5).setResizable(false);
            TablaVentas.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 500));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane3.setBorder(null);

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Origen", "Procesador", "Monto", "ID", "Correo", "Fecha", "Directorio"
            }
        ));
        jXTable1.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));
        Theader=jXTable1.getTableHeader();
        ((JLabel)Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        jXTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jXTable1.setAutoStartEditOnKeyStroke(false);
        jXTable1.setAutoscrolls(false);
        jXTable1.setComponentPopupMenu(jPopupMenuCompras);
        jXTable1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jXTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jXTable1.setRowHeight(30);
        jXTable1.setRowMargin(15);
        jXTable1.setShowHorizontalLines(false);
        jXTable1.setShowVerticalLines(false);
        jScrollPane3.setViewportView(jXTable1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 500));

        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N

        TablaExchange.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Origen", "Enviaste P", "Recibiste P", "Enviaste M", "Recibiste M", "ID", "Correo", "Fecha", "Directorio"
            }
        ));
        TablaExchange.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));
        TablaExchange.setShowGrid(false, false);
        Theader=TablaExchange.getTableHeader();
        ((JLabel)Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        TablaExchange.setComponentPopupMenu(jPopupExchange);
        TablaExchange.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        TablaExchange.setGridColor(new java.awt.Color(255, 255, 255));
        TablaExchange.setRowHeight(30);
        TablaExchange.setSelectionBackground(new java.awt.Color(231, 76, 60));
        jScrollPane2.setViewportView(TablaExchange);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 500));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void BuscarComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarComprasKeyTyped
        
        BuscarCompras.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent evt) {
                String cadena = (BuscarCompras.getText());
                BuscarCompras.setText(cadena);
                repaint();
                filtroCompras();
                toUpperCase(BuscarVentas, evt);
            }
        });
        trsfiltro = new TableRowSorter(jXTable1.getModel());
        jXTable1.setRowSorter(trsfiltro);

    }//GEN-LAST:event_BuscarComprasKeyTyped

    private void ComprasBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasBorrarMousePressed
        int n=0;
        n=JOptionPane.showConfirmDialog(rootPane, "Esta acción borrara todas las "
                + "compras registradas. ¿ Esta seguro de que desea continuar?",
                "Borrar Compras", JOptionPane.YES_NO_OPTION);
        
        if(n==0){
        control.borrar(ficheroCompras);
        limpiarTableCompras();
        }
    }//GEN-LAST:event_ComprasBorrarMousePressed

    private void AñadirCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirCompraMousePressed
        try {
            RegistroCompras compras=new RegistroCompras();
            compras.setVisible(true);
            this.dispose();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AñadirCompraMousePressed

    private void BotonInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMousePressed
        Home1 home = new Home1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonInicioMousePressed

    private void jLabeltotalVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeltotalVentasMouseClicked
         
    }//GEN-LAST:event_jLabeltotalVentasMouseClicked

    @SuppressWarnings("unchecked")
    private void BuscarVentasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarVentasKeyTyped
        
        BuscarVentas.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyReleased(final KeyEvent evt) {
                String cadena = (BuscarVentas.getText());
                BuscarVentas.setText(cadena);
                repaint();
                filtroVentas();
                toUpperCase(BuscarVentas, evt);
            }
        });
        trsfiltro = new TableRowSorter(TablaVentas.getModel());
        TablaVentas.setRowSorter(trsfiltro);
        
        
    }//GEN-LAST:event_BuscarVentasKeyTyped

    private void VentasBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasBorrarMousePressed
        int n;
        n=JOptionPane.showConfirmDialog(rootPane, "Esta acción borrara todas las "
                + "ventas registradas. ¿Esta seguro de que desea continuar?", 
                "Borrar ventas", JOptionPane.YES_NO_OPTION);
        
        if(n==0){
       
        control.borrar(ficheroVentas);
        
        limpiarTableVentas();
        }
    }//GEN-LAST:event_VentasBorrarMousePressed

    private void AñadirVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirVentaMousePressed
       RegistroVentas ventanaVentas=new RegistroVentas();
       ventanaVentas.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_AñadirVentaMousePressed

    private void AbrirComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirComprasActionPerformed
        String s=(String) jXTable1.getValueAt(jXTable1.getSelectedRow(), 7);
        File file=new File(s);
        Desktop desktop=Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AbrirComprasActionPerformed

    private void tabComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabComprasMousePressed
       if(ficheroCompras.exists()){
        comprasTab();
       }else{
           JOptionPane.showMessageDialog(rootPane, "Debe añadir una Compra", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_tabComprasMousePressed

    private void tabVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVentasMousePressed
       if(ficheroVentas.exists()){
        ventasTab();
       }else{
        JOptionPane.showMessageDialog(rootPane, "Debe añadir una Venta", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tabVentasMousePressed

    private void tabExchangeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabExchangeMousePressed
      if(ficheroExchange.exists()){
        exchangeTab();
      }else{
          JOptionPane.showMessageDialog(rootPane, "Debe añadir un Exchange", "Error", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_tabExchangeMousePressed

    private void AbrirVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbrirVentaMousePressed
        String s=(String) TablaVentas.getValueAt(TablaVentas.getSelectedRow(), 7);
        File file=new File(s);
        Desktop desktop=Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AbrirVentaMousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        String s=(String) TablaExchange.getValueAt(TablaExchange.getSelectedRow(), 9);
        File file=new File(s);
        Desktop desktop=Desktop.getDesktop();
        try {
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void BuscarExchangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarExchangeKeyTyped
         BuscarExchange.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyReleased(final KeyEvent evt) {
                String cadena = (BuscarExchange.getText());
                BuscarExchange.setText(cadena);
                repaint();
                filtroExchange();
                toUpperCase(BuscarExchange, evt);
            }
        });
        trsfiltro = new TableRowSorter(TablaExchange.getModel());
        TablaExchange.setRowSorter(trsfiltro);
    }//GEN-LAST:event_BuscarExchangeKeyTyped

    private void AñadirExchangeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirExchangeMousePressed
        new Exchange().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AñadirExchangeMousePressed

    private void ExchangeBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExchangeBorrarMousePressed
       int n;
        n=JOptionPane.showConfirmDialog(rootPane, "Esta acción borrara todas los "
                + "exchanges registrados. ¿Esta seguro de que desea continuar?", 
                "Borrar exchanges", JOptionPane.YES_NO_OPTION);
        
        if(n==0){
       
        control.borrar(ficheroExchange);
        
        limpiarTablaExchange();
        }
    }//GEN-LAST:event_ExchangeBorrarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirCompras;
    private javax.swing.JMenuItem AbrirVenta;
    private javax.swing.JLabel AñadirCompra;
    private javax.swing.JLabel AñadirExchange;
    private javax.swing.JLabel AñadirVenta;
    private javax.swing.JLabel BotonInicio;
    private javax.swing.JTextField BuscarCompras;
    private javax.swing.JTextField BuscarExchange;
    private javax.swing.JTextField BuscarVentas;
    private javax.swing.JLabel ComprasBorrar;
    private javax.swing.JLabel ExchangeBorrar;
    private org.jdesktop.swingx.JXTable TablaExchange;
    private org.jdesktop.swingx.JXTable TablaVentas;
    private javax.swing.JLabel TituloVentana;
    private javax.swing.JLabel VentasBorrar;
    private javax.swing.JLabel buscarIcono;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeltotalCompra;
    private javax.swing.JLabel jLabeltotalVentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupExchange;
    private javax.swing.JPopupMenu jPopupMenuCompras;
    private javax.swing.JPopupMenu jPopupMenuVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JLabel montoTotalCompras;
    private javax.swing.JLabel montoTotalVentas;
    private javax.swing.JPanel tabCompras;
    private javax.swing.JPanel tabExchange;
    private javax.swing.JPanel tabVentas;
    // End of variables declaration//GEN-END:variables
        
   
    //<editor-fold defaultstate="collapsed" desc="comment">
    @SuppressWarnings
//</editor-fold>
({"unchecked", "unchecked"})
    private void filtroCompras(){
       String filtro=BuscarCompras.getText();
       if (jComboBox2.getSelectedItem()=="Usuario"){
           int columna=0;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }else if(jComboBox2.getSelectedItem()=="Origen"){
           int columna=1;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       } else if(jComboBox2.getSelectedItem()=="ID"){
           int columna=4;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }
       else if(jComboBox2.getSelectedItem()=="Fecha"){
           int columna=6;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }
    }    
    @SuppressWarnings("unchecked")
    private void filtroVentas(){
        String filtro=BuscarVentas.getText();
       if (jComboBox2.getSelectedItem()=="Usuario"){
           int columna=0;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }else if(jComboBox2.getSelectedItem()=="Origen"){
           int columna=1;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }else if(jComboBox2.getSelectedItem()=="ID"){
           int columna=4;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }
       else if(jComboBox2.getSelectedItem()=="Fecha"){
           int columna=6;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }
    }
    private void filtroExchange(){
          String filtro=BuscarExchange.getText();
       if (jComboBox2.getSelectedItem()=="Usuario"){
           int columna=0;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }else if(jComboBox2.getSelectedItem()=="Origen"){
           int columna=1;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }else if(jComboBox2.getSelectedItem()=="ID"){
           int columna=4;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }
       else if(jComboBox2.getSelectedItem()=="Fecha"){
           int columna=6;
           trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
       }
    }
    
    private void cargarTablaCompras() throws IOException, ClassNotFoundException, IOException{

        if(ficheroCompras.exists()){  
            MatricesHistorial tablaHistorialCompras = new MatricesHistorial(); 
            String [][]MatrizCompra=tablaHistorialCompras.cargarArrayTablaCompras();
        
        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
        MatrizCompra,
        new String [] {
                "Usuario", "Origen","Procesador", "Monto $","ID", "E-Mail", "Fecha", "Directorio"
            }
        ){
                private static final long serialVersionUID = 1L;
            boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false, false
        };
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
            }
        });
                jXTable1.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));
                JTableHeader Theader=jXTable1.getTableHeader();
                ((JLabel)Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
                
                
                sumarSaldoCompras();
        }
                jXTable1.setShowGrid(false, false);
        if (jXTable1.getColumnModel().getColumnCount() > 0) {
    jXTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
    jXTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
    jXTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
    jXTable1.getColumnModel().getColumn(3).setPreferredWidth(20);

}
        
} 
    private void cargarTablaVentas() throws ClassNotFoundException, IOException{
        
        if (ficheroVentas.exists()){
        MatricesHistorial tablaHistorialVentas=new MatricesHistorial();
        String [][]datosVentas=tablaHistorialVentas.cargarArrayTablaVentas();
        
         TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
        datosVentas,
    new String [] {
        "Usuario", "Origen", "Procesador", "Monto $", "ID", "Correo", "Fecha","Directorio"
    }
) {
            private static final long serialVersionUID = 1L;
    boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false
    };
            @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
        });
        TablaVentas.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));     
               
                 TablaVentas.setShowGrid(false, false);
                JTableHeader Theader=TablaVentas.getTableHeader();
                ((JLabel)Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        sumarSaldoVentas();
        }
    }
    private void cargarTablaExchange() throws ClassNotFoundException, IOException{
         if (ficheroExchange.exists()){
        MatricesHistorial tablaHistorialVentas=new MatricesHistorial();
        String [][]datosExchange=tablaHistorialVentas.cargarArrayTablaExchange();
        
         TablaExchange.setModel(new javax.swing.table.DefaultTableModel(
        datosExchange,
    new String [] {
        "Usuario", "Origen", "Enviaste P", "Recibiste P", "Enviaste M", "Recibiste M", "ID", "Correo", "Fecha", "Directorio"
    }
) {
            private static final long serialVersionUID = 1L;
    boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false
    };
            @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
        });
        TablaExchange.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));     
        TablaExchange.setShowGrid(false, false);
                JTableHeader Theader=TablaExchange.getTableHeader();
                ((JLabel)Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
      //  sumarSaldoVentas();
         }       
                 
    }
    
            
    private void limpiarTableCompras(){
       
    jXTable1.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {
        },
    new String [] {
        "Usuario", "Origen","Procesador", "Monto $","ID", "E-Mail", "Fecha", "Directorio"
    }
));
    jXTable1.getTableHeader().setFont(new Font("Microsoft jhenghei", Font.BOLD, 14));
    montoTotalCompras.setText("");
}
    private void limpiarTableVentas(){
    TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
        "Usuario", "Origen", "Procesador", "Monto $", "ID", "Correo", "Fecha","Directorio"
    }
));
    montoTotalVentas.setText("");
    }
    private void limpiarTablaExchange(){
            TablaExchange.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
      "Usuario", "Origen", "Enviaste P", "Recibiste P", "Enviaste M", "Recibiste M", "ID", "Correo", "Fecha", "Directorio"
    }
));
    }
    
    private void toUpperCase(JTextField field,java.awt.event.KeyEvent evt){
        field= (JTextField)evt.getComponent();

    String texto=field.getText();//para evitar espacios en blanco antes y despues del texto
    if(texto.length()>0){
    char primero=texto.charAt(0);
    texto=Character.toUpperCase(primero)+texto.substring(1, texto.length());
    field.setText(texto);
    }
    }
    private void exchangeTab(){
       tabExchange.setBackground(new java.awt.Color(231,76,60));
       tabCompras.setBackground(new java.awt.Color(55,71,79));
       tabVentas.setBackground(new java.awt.Color(55,71,79));
       jScrollPane2.setVisible(true);
       jScrollPane3.setVisible(false);
       jPanel5.setVisible(false);
       montoTotalVentas.setVisible(false);
       montoTotalCompras.setVisible(false);
       BuscarExchange.setVisible(true);
       BuscarVentas.setVisible(false);
       BuscarCompras.setVisible(false);
       AñadirExchange.setVisible(true);
       ExchangeBorrar.setVisible(true);
       VentasBorrar.setVisible(false);
       AñadirCompra.setVisible(false);
       AñadirVenta.setVisible(false); 
       ComprasBorrar.setVisible(false);
       jLabeltotalCompra.setVisible(false);
       jLabeltotalVentas.setVisible(false);
    }
    private void comprasTab(){
       tabCompras.setBackground(new java.awt.Color(0,120,215));
       tabVentas.setBackground(new java.awt.Color(55,71,79));
       tabExchange.setBackground(new java.awt.Color(55,71,79));
   
       jPanel5.setVisible(false);
       jScrollPane3.setVisible(true);
       jLabeltotalCompra.setVisible(true);
       jLabeltotalVentas.setVisible(false);
       BuscarVentas.setVisible(false);
       BuscarCompras.setVisible(true);
       montoTotalVentas.setVisible(false);
       montoTotalCompras.setVisible(true);
       ComprasBorrar.setVisible(true);
       VentasBorrar.setVisible(false);
       AñadirCompra.setVisible(true);
       AñadirVenta.setVisible(false);
       BuscarExchange.setVisible(false);
       AñadirExchange.setVisible(false);
       ExchangeBorrar.setVisible(false);
    }
    private void ventasTab(){
       tabVentas.setBackground(new java.awt.Color(39,174,96));
       tabCompras.setBackground(new java.awt.Color(55,71,79));
       tabExchange.setBackground(new java.awt.Color(55,71,79));
       jScrollPane3.setVisible(false);
       jPanel5.setVisible(true);
       jLabeltotalVentas.setVisible(true);
       jLabeltotalCompra.setVisible(false);
       BuscarVentas.setVisible(true);
       BuscarCompras.setVisible(false);
       montoTotalVentas.setVisible(true);
       montoTotalCompras.setVisible(false);
       ComprasBorrar.setVisible(false);
       VentasBorrar.setVisible(true);
       AñadirCompra.setVisible(false);
       AñadirVenta.setVisible(true);
       BuscarExchange.setVisible(false);
       AñadirExchange.setVisible(false);
       ExchangeBorrar.setVisible(false);
    }
    
    public void sumarSaldoVentas(){
        double sumatoria1=0.0;
        int totalRow= TablaVentas.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
             double sumatoria= Double.parseDouble(String.valueOf(TablaVentas.getValueAt(i,3)));
//en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual estaras //manejando
             sumatoria1+=sumatoria;
             String sumatoria2=String.valueOf(sumatoria1);
 
            montoTotalVentas.setText(sumatoria2+"$");
 
           }
    }
    public void sumarSaldoCompras(){
        double sumatoria1=0.0;
        int totalRow= jXTable1.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
             double sumatoria= Double.parseDouble(String.valueOf(jXTable1.getValueAt(i,3)));
//en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual estaras //manejando
             sumatoria1+=sumatoria;
             String sumatoria2=String.valueOf(sumatoria1);
 
            montoTotalCompras.setText(sumatoria2+"$");
 
           }
    }
    
    private void centrar(int column, JTable table){
DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
tcr.setHorizontalAlignment(SwingConstants.CENTER);
table.getColumnModel().getColumn(column).setCellRenderer(tcr);
    }
    private void placeHolder(){
        TextPrompt buscarC=new TextPrompt("Buscar...",BuscarCompras);
        TextPrompt buscarV=new TextPrompt("Buscar...",BuscarVentas);
        TextPrompt buscarE=new TextPrompt("Buscar...",BuscarExchange);
    }

    
    public void iniVentas(){
        
    }
    
}
