/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import walletcontrol.ControlVentas;


/**
 *
 * @author Eduardo Perfecto
 */
public class RegistroVentas extends javax.swing.JFrame {
private ControlVentas control=new ControlVentas();

    public RegistroVentas() {
        initComponents();
        setLocationRelativeTo(null);
        PlaceHolder();
    }
    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vistas/Logounico.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonInicio = new javax.swing.JLabel();
        botonHistorial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        origen = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Limpiar = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        usuario = new javax.swing.JTextField();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Save_35px.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));

        botonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Home_24px.png"))); // NOI18N
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonInicioMousePressed(evt);
            }
        });

        botonHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Literature_26px.png"))); // NOI18N
        botonHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonHistorialMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar ventas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(botonInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonHistorial)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonInicio)
                            .addComponent(botonHistorial)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_User_24px_1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 31, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Contact_24px_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 107, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Check_24px_1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 185, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Calendar_3_24px.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 251, -1, -1));

        nombre.setBackground(new java.awt.Color(245, 245, 245));
        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(null);
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 107, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Contact_24px_1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Marker_24px_1.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Email_24px_3.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        apellido.setBackground(new java.awt.Color(245, 245, 245));
        apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apellido.setForeground(new java.awt.Color(102, 102, 102));
        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido.setBorder(null);
        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoKeyTyped(evt);
            }
        });
        jPanel2.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 90, -1));

        correo.setBackground(new java.awt.Color(245, 245, 245));
        correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(102, 102, 102));
        correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo.setBorder(null);
        correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoFocusGained(evt);
            }
        });
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoMouseClicked(evt);
            }
        });
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoKeyTyped(evt);
            }
        });
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, -1));

        origen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        origen.setForeground(new java.awt.Color(51, 51, 51));
        origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Foro-PTC", "Instagram", "Facebook", " " }));
        origen.setToolTipText("Pagina web donde se origino la venta");
        jPanel2.add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jDateChooser1.setBackground(new java.awt.Color(245, 245, 245));
        jDateChooser1.setDateFormatString("MMM d yyyy");
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 255, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 54, 90, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 130, 90, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 54, 67, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 90, 10));

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Erase_30px.png"))); // NOI18N
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LimpiarMousePressed(evt);
            }
        });
        jPanel2.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        ID.setBackground(new java.awt.Color(245, 245, 245));
        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(102, 102, 102));
        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID.setToolTipText("ID de la transaccion generado por el procesador usado");
        ID.setBorder(null);
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 185, 90, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 208, 90, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Images/icons8_Save_30px.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        monto.setBackground(new java.awt.Color(245, 245, 245));
        monto.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        monto.setForeground(new java.awt.Color(0, 102, 204));
        monto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monto.setBorder(null);
        monto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montoFocusGained(evt);
            }
        });
        monto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                montoMouseClicked(evt);
            }
        });
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
        });
        jPanel2.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 110, 38));

        jSeparator7.setForeground(new java.awt.Color(0, 102, 204));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 120, 10));

        usuario.setBackground(new java.awt.Color(245, 245, 245));
        usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(102, 102, 102));
        usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuario.setBorder(null);
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 31, 90, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 330, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHistorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHistorialMousePressed
         try {
             Historial historial=new Historial();
             historial.setVisible(true);
             this.dispose();
         } catch (IOException | ClassNotFoundException ex) {
             Logger.getLogger(RegistroVentas.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_botonHistorialMousePressed

    private void botonInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMousePressed
        Home1 home=new Home1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonInicioMousePressed

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped
        toUpperCase(usuario,evt);
    }//GEN-LAST:event_usuarioKeyTyped

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c) && c!='.'){
            evt.consume();
        }
        if(Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_montoKeyTyped

    private void montoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montoMouseClicked
        monto.setText("");
    }//GEN-LAST:event_montoMouseClicked

    private void montoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montoFocusGained
        monto.setText("");
    }//GEN-LAST:event_montoFocusGained

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        if(!verificarCampos()){
            try{
                String anadirOrigen ="";

                if(origen.getSelectedItem()=="Instagram"){
                    anadirOrigen="Instagram";
                }
                if(origen.getSelectedItem()=="Facebook"){
                    anadirOrigen="Facebook";
                }
                if (origen.getSelectedItem()=="Foro-PTC"){

                    anadirOrigen="Foro-PTC";
                }

                String fecha1=jDateChooser1.getDate().toString();
                String usuario1=usuario.getText();
                String nombre1=nombre.getText();
                String apellido1=apellido.getText();
                String ID1=ID.getText();
                String monto1=monto.getText();
                String correo1=correo.getText();

                SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd yyyy");
                fecha1 = dateFormat.format(jDateChooser1.getDate());
                String fecha2=fecha1.toUpperCase();

                int n=JOptionPane.showConfirmDialog(rootPane, "Esta seguro de que todos los "
                    + "datos son correctos?", "Confirmacion", JOptionPane.YES_NO_OPTION);

                if(n==0){

                    control.agregarVenta(usuario1,anadirOrigen,nombre1,apellido1,correo1,ID1,
                        monto1,fecha2);

                    JOptionPane.showMessageDialog(rootPane, "Venta añadida", "Compras",
                        JOptionPane.INFORMATION_MESSAGE);

                    limpiarCampos();

                }
            }catch(NullPointerException e){
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar una fecha",
                    "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            }
        }else{JOptionPane.showMessageDialog(rootPane, "Datos incompletos",
            "Datos Incompletos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel11MousePressed

    private void LimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMousePressed
        limpiarCampos();
    }//GEN-LAST:event_LimpiarMousePressed

    private void correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyTyped
        toUpperCase(correo,evt);
    }//GEN-LAST:event_correoKeyTyped

    private void correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMouseClicked
        correo.setText("");
    }//GEN-LAST:event_correoMouseClicked

    private void correoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFocusGained
        correo.setText("");
    }//GEN-LAST:event_correoFocusGained

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyTyped

        char c=evt.getKeyChar();

        if(Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
        toUpperCase(apellido,evt);

    }//GEN-LAST:event_apellidoKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

        }
        toUpperCase(nombre,evt);
    }//GEN-LAST:event_nombreKeyTyped

    private void toUpperCase(JTextField field,java.awt.event.KeyEvent evt){
        field= (JTextField)evt.getComponent();

    String texto=field.getText().trim();//para evitar espacios en blanco antes y despues del texto
    if(texto.length()>0){
    char primero=texto.charAt(0);
    texto=Character.toUpperCase(primero)+texto.substring(1, texto.length());
    field.setText(texto);
    }
    }
    
    private void PlaceHolder()    {
    TextPrompt user = new TextPrompt("     Usuario", usuario);
    TextPrompt name = new TextPrompt("     Nombre",nombre);
    name.setShow(TextPrompt.Show.FOCUS_LOST);
    TextPrompt lastName = new TextPrompt("     Apellido",apellido);
    lastName.setShow(TextPrompt.Show.FOCUS_LOST);
    TextPrompt id= new TextPrompt ("         ID",ID);
    id.setShow(TextPrompt.Show.FOCUS_LOST);
    TextPrompt mail=new TextPrompt("     Correo",correo);
    mail.setShow(TextPrompt.Show.FOCUS_LOST);
    TextPrompt monto2=new TextPrompt("   0.0$",monto);
    monto2.setShow(TextPrompt.Show.FOCUS_LOST);
} 
    
      private boolean verificarCampos(){
        boolean r=usuario.getText().isEmpty();
        r|=nombre.getText().isEmpty();
        r|=apellido.getText().isEmpty();
        r|=ID.getText().isEmpty();
        r|=correo.getText().isEmpty();
        r|=monto.getText().isEmpty();
        
        return r;
    }
      private void limpiarCampos(){
        usuario.setText("");
        monto.setText("");
        correo.setText("");
        ID.setText("");
        apellido.setText("");
        nombre.setText("");
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JLabel Limpiar;
    private javax.swing.JTextField apellido;
    private javax.swing.JLabel botonHistorial;
    private javax.swing.JLabel botonInicio;
    private javax.swing.JTextField correo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> origen;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
